FROM python:3.11-alpine

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0
ENV C_FORCE_ROOT true

ENV HOST 0.0.0.0
ENV PORT 8000
ENV DEBUG true

RUN apk update
RUN apk add postgresql-dev gcc python3-dev musl-dev

WORKDIR /backend
COPY requirements.txt .

RUN pip install -U setuptools pip
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]